services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing-php
    ports:
      - 80:80
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./contact.php:/var/www/html/contact.php
      - ./styles/:/var/www/html/styles
    restart: always